name: CI
on: [push, pull_request]
defaults:
  run:
    shell: cmd
jobs:
  build:
    # Skip building pull requests from the same repository
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository) }}
    name: Windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        dotnet-version: ['6.0.x']
        platform: 
          - {arch: 'x86', dir: 'x32'}
          - {arch: 'x64', dir: 'x64'}
    env:
      CONFIGURATION: Release
      PLATFORM: ${{ matrix.platform.arch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Nuget dependencies
        run: |
          cd src
          msbuild Dotx64Dbg.sln -t:restore -p:RestorePackagesConfig=true -maxcpucount:2 /m
          IF %ERRORLEVEL% NEQ 0 (
            ECHO MSBuild for Debug x64 returned error code %ERRORLEVEL%
            EXIT /B %ERRORLEVEL%
          )
          cd ..
      - name: Build
        run: |
          cd src
          msbuild Dotx64Dbg.sln /p:platform=${{ matrix.platform.arch }} /m
          IF %ERRORLEVEL% NEQ 0 (
            ECHO MSBuild for Debug x64 returned error code %ERRORLEVEL%
            EXIT /B %ERRORLEVEL%
          )
          cd ..
      - name: Tests
        run: |
          pushd .
          cd bin\${{ matrix.platform.dir }}\tests
          Tests.exe
          popd
      - name: Upload artifacts (CI)
        uses: actions/upload-artifact@v2
        with:
          name: dotx64Dbg-${{ runner.os }}-${{ matrix.platform.arch }}
          path: bin
          if-no-files-found: error
  package:
    needs: build
    name: Package
    runs-on: ubuntu-latest
    steps:
      - name: Fetch artifacts 
        uses: actions/download-artifact@v4.1.7
        with: 
          path: artifacts
      - name: Display structure of downloaded files
        shell: bash
        run: ls -R
        working-directory: artifacts
      - name: Merge artifacts
        shell: bash
        run: |
          mkdir package
          cp -R -n ./artifacts/dotx64Dbg-Windows-x64/* ./package/
          cp -R -n ./artifacts/dotx64Dbg-Windows-x86/* ./package/
          rm -R ./package/x32/tests
          rm -R ./package/x64/tests
          find ./package -type f -name '*.pdb' -delete
          find ./package -type f -name '*.lib' -delete
          find ./package -type f -name '*.exp' -delete
          find ./package -type f -name '*.ilk' -delete
      - name: Upload package (CI)
        uses: actions/upload-artifact@v2
        with:
          name: dotx64dbg
          path: package
          if-no-files-found: error
      - name: Compress artifacts
        uses: papeloto/action-zip@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          files: package/
          dest: ${{ github.event.repository.name }}-${{ github.ref_name }}.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          prerelease: ${{ !startsWith(github.ref, 'refs/tags/v') || contains(github.ref, '-pre') }}
          files: ${{ github.event.repository.name }}-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}